export const Traits = [
    { value: '1', label: "Archaeologist", description: "Must find the bone as a priority. Can't do anything else until it is found" },
    { value: '2', label: "Atmospheric", description: "Can only use the candle for light" },
    { value: '3', label: "Back Pain", description: "Must crouch at all times after the truck door is opened for the first time" },
    { value: '4', label: "Bartender", description: "Must bring all drinks on the map to the ghost room" },
    { value: '5', label: "Bold", description: "Can’t use the crucifix" },
    { value: '6', label: "Chatterbox", description: "Must always talk to the ghost when near it, say its name, ask for signs, etc. including during hunts" },
    { value: '7', label: "Chef", description: "Must bring all plates and cutlery on the map to the ghost room" },
    { value: '8', label: "Chilly", description: "Must keep the breaker on at all times" },
    { value: '9', label: "Clumsy", description: "Drop all items when a hunt begins" },
    { value: '10', label: "Courteous", description: "You must close every door behind you, including during hunts" },
    { value: '11', label: "Coward", description: "If you experience a ghost event, you must leave instantly and guess based on the current evidence and ghost " },
    { value: '12', label: "Deafened", description: "No sound when playing this character" },
    { value: '13', label: "Disorientated", description: "Headphones are reversed when playing this character" },
    { value: '14', label: "Forgetful", description: " Two random unlocked items have been forgotten, and are banned this mission. Spin the wheel to decide which items" },
    { value: '15', label: "Germophobe", description: "Must wash your hands every time you directly pass a sink, or a room with a sink" },
    { value: '16', label: "Impulsive", description: " If there is a ghost event, the character must drop whatever item is in their hand out of fear. This item is now " },
    { value: '17', label: "Inconsiderate", description: "Every door you pass must be left wide open, including during hunts" },
    { value: '18', label: "Inquisitive", description: "If the Ouija board is found, you immediately have to use it until you get a successful answer" },
    { value: '19', label: "Insane", description: "Never allowed to check sanity on the truck monitor" },
    { value: '20', label: "Limp", description: "Can’t sprint during hunts" },
    { value: '21', label: "Nycotophobic", description: " Building Lights have to stay on in the current room you are in at all times. If the breaker goes off, go get it back on ASAP" },
    { value: '22', label: "Oversized", description: "Can’t hide in lockers or closets" },
    { value: '23', label: "Paranoid", description: "Can’t hide in the same place more than once per mission (includes furniture, lockers and closets)" },
    { value: '24', label: "Perceptive", description: "Must use eyes and ears only to find and confirm the ghost room" },
    { value: '25', label: "Pharmacophobic", description: "Can’t take sanity pills" },
    { value: '26', label: "Photophobic", description: "No building lights are allowed" },
    { value: '27', label: "Raver", description: "Can only use glowsticks for light" },
    { value: '28', label: "Reckless", description: "Can’t use smudge sticks" },
    { value: '29', label: "Rushed", description: "Not allowed to check the breaker location on the truck monitor" },
    { value: '30', label: "Shy", description: "Not allowed to talk to the ghost (this includes the Spirit Box and Ouija Board)" },
    { value: '31', label: "Small pockets", description: "Can only carry 2 items" },
    { value: '32', label: "Thick jumper", description: "Must keep the breaker off at all times" },
    { value: '33', label: "Tidy", description: "Must put every item back where it belongs if the ghost disturbs or throws them" },
    { value: '34', label: "Unprepared", description: "Can’t look at any information on the whiteboard (ghost name & optional objectives)" },
    { value: '35', label: "Useless", description: "Can’t use any evidence gathering equipment" },
    { value: '36', label: "UV expert", description: "Can only use the UV torch for light" },
    { value: '37', label: "Weak bladder", description: "Must use the toilet every time you directly pass a room with a toilet in" },
    { value: '38', label: "Young at heart", description: "Must rescue any stuffed toys and bring them back to the truck" }
]

export const Items = [
    { value: '1', label: 'Candle' },
    { value: '2', label: 'Crucifix' },
    { value: '3', label: 'EMF Reader' },
    { value: '4', label: 'Flashlight' },
    { value: '5', label: "Ghost Writing Book" },
    { value: '6', label: 'Glow Stick' },
    { value: '7', label: 'Head Mounted Camera' },
    { value: '8', label: 'Infrared Light Sensor' },
    { value: '9', label: 'Lighter' },
    { value: '10', label: 'Motion Sensor' },
    { value: '11', label: 'Parabolic Microphone' },
    { value: '12', label: 'Photo Camera' },
    { value: '13', label: 'Salt' },
    { value: '14', label: 'Sanity Pills' },
    { value: '15', label: 'Spirit Box' },
    { value: '16', label: 'Smudge Stick' },
    { value: '17', label: 'Sound Sensor'},
    { value: '18', label: 'Strong Flashlight' },
    { value: '19', label: 'Thermometer' },
    { value: '20', label: 'Tripod' },
    { value: '21', label: 'UV Flashlight' },
    { value: '22', label: 'Video Camera' }
]